### ISSUE TITLE
Documentation: installation

### ISSUE THREAD

**Issue by jamesdalg** [ComputationalIntelligenceGroup/Map_tools#7]
In the instructions, it says "Installation
As every imageJ plugin just add the .jar into the plugin directory." Where precisely is the .jar file? Is this something that should be assembled?

**Comment by gherardovarando** [comment]
The .jar can be downloaded from the releases [page](https://github.com/ComputationalIntelligenceGroup/Map_tools/releases), moreover the [json-simple-1.1.1.jar](https://github.com/ComputationalIntelligenceGroup/Map_tools/releases/download/v1.1.0/json-simple-1.1.1.jar) has to be copied into a lib folder into the plugins directory. 

(README.md updated with info)

**Comment by gherardovarando** [comment]
Also it is possible to install the plugin and the json-simple dependencies directly using the ImageJ updater from the following update site 
http://sites.imagej.net/Cig-upm/
